---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoPlugin: "my-plugin"
    entando.org/entando-resource-namespace: "my-namespace"
    entando.org/entando-resource-kind: "EntandoPlugin"
  name: "my-plugin-93115558"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoPlugin"
    blockOwnerDeletion: true
    controller: true
    name: "my-plugin"
    uid: "9b40cf04-8891-4167-bdf5-8fd0a39b9d5b"
action: "FAILED"
count: 1
firstTimestamp: "2021-10-26T19:29:06Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoPlugin"
  fieldPath: "status"
  name: "my-plugin"
  namespace: "my-namespace"
  resourceVersion: "5255646"
  uid: "9b40cf04-8891-4167-bdf5-8fd0a39b9d5b"
lastTimestamp: "2021-10-26T19:29:06Z"
message: "The deployment of EntandoPlugin my-namespace/my-plugin failed due to Fake\
  \ Controller Exception. Fix the root cause and then trigger a redeployment by adding\
  \ the annotation 'entando.org/processing-instruction: force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-plugin-xs4rv-2-from-build-pack-42-wjn9n"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-plugin-controller"
type: "Error"
