---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoPlugin: "my-plugin"
    entando.org/entando-resource-namespace: "my-namespace"
    entando.org/entando-resource-kind: "EntandoPlugin"
  name: "my-plugin-05952732"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoPlugin"
    blockOwnerDeletion: true
    controller: true
    name: "my-plugin"
    uid: "94368a53-7e41-4c07-8974-e9b20d6c59b5"
action: "FAILED"
count: 1
firstTimestamp: "2021-10-31T22:57:08Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoPlugin"
  fieldPath: "status"
  name: "my-plugin"
  namespace: "my-namespace"
  resourceVersion: "7680974"
  uid: "94368a53-7e41-4c07-8974-e9b20d6c59b5"
lastTimestamp: "2021-10-31T22:57:08Z"
message: "The deployment of EntandoPlugin my-namespace/my-plugin failed due to Fake\
  \ Controller Exception. Fix the root cause and then trigger a redeployment by adding\
  \ the annotation 'entando.org/processing-instruction: force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-plugin-ch9nc-24-from-build-pack-8-n7mb5"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-plugin-controller"
type: "Error"
