---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    entando.org/entando-resource-namespace: "my-namespace"
    TestResource: "my-app"
    entando.org/entando-resource-kind: "TestResource"
  name: "my-app-52992437"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "test.org/v1"
    kind: "TestResource"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "0e80110c-3ceb-44f3-bce4-82d0fcffa8e8"
action: "FAILED"
count: 1
firstTimestamp: "2021-11-26T13:00:43Z"
involvedObject:
  apiVersion: "test.org/v1"
  kind: "TestResource"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "8775509"
  uid: "0e80110c-3ceb-44f3-bce4-82d0fcffa8e8"
lastTimestamp: "2021-11-26T13:00:43Z"
message: "The deployment of TestResource my-namespace/my-app failed due to Database\
  \ preparation failed. Please inspect the logs of the pod my-namespace/my-app-dbprep-2ed3.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "test-controller-pod"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-ource-controller"
type: "Error"
